server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
        
        
# Define the Eureka server that handles service registration
eureka:
  instance:
    hostname: localhost
    port: 8010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#database:
spring:  data:    mongodb:      host: 127.0.0.1
      database: dashboard        